#!/bin/bash

# NeurX Code 自动滚动诊断脚本

echo "🔍 NeurX Code Agent 自动滚动诊断"
echo "===================================="
echo ""

echo "📋 问题分析："
echo "• 问题: Agent 现在不能自动滚动屏幕"
echo "• 受影响的功能: ChatPanel 自动跟随最新消息"
echo ""

echo "🔧 诊断信息:"
echo ""

echo "1️⃣ 检查 ChatPanel.qml 滚动逻辑:"
echo "   - autoFollowLatest 初始值: true"
echo "   - scrollToBottom() 在以下情况被调用:"
echo "     • onCountChanged (消息数量改变)"
echo "     • onContentHeightChanged (内容高度改变)"
echo "     • onContentYChanged (内容Y位置改变)"
echo "     • onBusyChanged (忙碌状态改变)"
echo "     • onStreamingTextChanged (流式文本改变)"
echo ""

echo "2️⃣ 可能的原因:"
echo "   ❌ autoFollowLatest = false (用户手动滚动时设置)"
echo "   ❌ busy = false 且 streamingText = '' (Agent 没有在回复)"
echo "   ❌ ListView 没有正确更新(消息没有添加)"
echo "   ❌ 信号没有被发出(连接问题)"
echo "   ❌ isListViewAtBottom() 返回 false (误判)"
echo ""

echo "3️⃣ 最近的修改影响分析:"
echo "   ✅ 工具注册修改不应影响 ChatPanel"
echo "   ✅ AgentController 构造函数修改不应影响消息处理"
echo "   ❓ 可能的间接影响:"
echo "     - 如果 busy 信号没有被正确发出"
echo "     - 如果 streamingText 没有被正确更新"
echo ""

echo "📝 故障排查步骤:"
echo ""
echo "第1步: 运行应用并检查日志中的信号发出"
echo "   QT_LOGGING_RULES='*=true' /path/to/neurx-codeApp"
echo "   查找:"
echo "   • [AgentController::onBusyChanged]"
echo "   • [ChatPanel] onBusyChanged"
echo "   • [ChatPanel] onStreamingTextChanged"
echo ""

echo "第2步: 测试自动滚动"
echo "   1. 打开应用"
echo "   2. 打开一个工作空间"
echo "   3. 在 Agent 中输入消息"
echo "   4. 观察消息列表是否自动滚动到底部"
echo ""

echo "第3步: 手动测试滚动恢复"
echo "   1. 手动向上滚动列表"
echo "   2. 观察 autoFollowLatest 是否变为 false"
echo "   3. 点击\"↓\"按钮回到底部"
echo "   4. 观察 autoFollowLatest 是否变为 true"
echo "   5. Agent 回复时是否自动滚动"
echo ""

echo "第4步: 检查消息是否被添加"
echo "   在日志中查找:"
echo "   • [ChatModel] append()"
echo "   • [AgentController::onMessageAdded]"
echo "   确保消息被正确添加到模型中"
echo ""

echo "👨‍💻 用户可以提供的信息:"
echo "   1. 具体现象: 新消息时不滚动? Agent 回复时不滚动? 两者都不滚动?"
echo "   2. 是否之前能滚动? 什么时候开始不能滚动的?"
echo "   3. 点击\"↓\"按钮能否回到底部?"
echo "   4. 应用启动时是否有错误信息?"
echo ""

echo "===================================="
echo "请运行诊断步骤并提供详细的现象描述。"
echo ""
