#!/bin/bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"
source "/Users/feifei/shuwen/train/neurx/production_deployment/training_startup.env"
export NEURX_PRETRAIN_USE_LAUNCH_PLAN=0
export NEURX_CLUSTER_DISABLE=1
NEURX_CLUSTER_NAME="$CLUSTER_NAME" NEURX_CLUSTER_BACKEND="$CLUSTER_BACKEND" NEURX_CLUSTER_WORLD_SIZE="$WORLD_SIZE" NEURX_CLUSTER_MASTER_ADDR="$MASTER_ADDR" NEURX_CLUSTER_MASTER_PORT="$MASTER_PORT" NEURX_CHECKPOINT_DIR="$CHECKPOINT_DIR" NEURX_TRAIN_OUTPUT_DIR="$OUTPUT_DIR" NEURX_PRETRAIN_OUTPUT_DIR="$NEURX_PRETRAIN_OUTPUT_DIR" NEURX_PRETRAIN_MANIFEST="$NEURX_PRETRAIN_MANIFEST" NEURX_PRETRAIN_TOKENIZER_MANIFEST="$NEURX_PRETRAIN_TOKENIZER_MANIFEST" NEURX_PRETRAIN_PRECISION="$NEURX_PRETRAIN_PRECISION" NEURX_PRETRAIN_MICRO_BATCH="$NEURX_PRETRAIN_MICRO_BATCH" NEURX_PRETRAIN_SEQ_LEN="$NEURX_PRETRAIN_SEQ_LEN" NEURX_PRETRAIN_STEPS="$NEURX_PRETRAIN_STEPS" NEURX_PRETRAIN_LR="$NEURX_PRETRAIN_LR" NEURX_PRETRAIN_MIN_LR="$NEURX_PRETRAIN_MIN_LR" NEURX_PRETRAIN_WARMUP_STEPS="$NEURX_PRETRAIN_WARMUP_STEPS" NEURX_PRETRAIN_WEIGHT_DECAY="$NEURX_PRETRAIN_WEIGHT_DECAY" NEURX_PRETRAIN_LOG_INTERVAL="$NEURX_PRETRAIN_LOG_INTERVAL" NEURX_PRETRAIN_EVAL_INTERVAL="$NEURX_PRETRAIN_EVAL_INTERVAL" NEURX_PRETRAIN_SAVE_INTERVAL="$NEURX_PRETRAIN_SAVE_INTERVAL" NEURX_PRETRAIN_GRAD_ACCUMULATION="$NEURX_PRETRAIN_GRAD_ACCUMULATION" NEURX_PRETRAIN_RESUME="$NEURX_PRETRAIN_RESUME" bash script/run_gpt_large_pretrain.sh
