package neurx.script
use std.fs
use std.os
use std.strings

struct training_config {
    string root_dir
    string hostfile
    string output_dir
    string master_addr
    int master_port
    string nccl_id_file
    int num_nodes
    int world_size
    int pretrain_steps
    int micro_batch
    int seq_len
    float learning_rate
    int log_interval
    int save_interval
    int transformer_dim
    int transformer_heads
    int transformer_ffn
    int transformer_layers
    int gradient_accumulation_steps
    string tokenizer_vocab
    string tokenizer_merges
    string shard_list_file
}

func load_config_from_env() training_config {
    training_config cfg
    string root = os_getenv("NEURX_ROOT")
    if root == "" {
        root = os_working_dir()
    }
    cfg.root_dir = root
    cfg.hostfile = os_getenv("NEURX_HOSTFILE")
    if cfg.hostfile == "" {
        cfg.hostfile = root + "/config/pretrain.hosts"
    }
    cfg.output_dir = os_getenv("NEURX_PRETRAIN_OUTPUT_DIR")
    if cfg.output_dir == "" {
        cfg.output_dir = root + "/checkpoint/NeurX-1.3"
    }
    cfg.nccl_id_file = os_getenv("NEURX_SHARED_NCCL_ID_FILE")
    if cfg.nccl_id_file == "" {
        cfg.nccl_id_file = root + "/artifact/nccl/unique_id"
    }
    cfg.master_addr = os_getenv("MASTER_ADDR")
    if cfg.master_addr == "" {
        cfg.master_addr = "localhost"
    }
    string port_str = os_getenv("MASTER_PORT")
    if port_str != "" {
        cfg.master_port = strings_parse_int(port_str)
    } else {
        cfg.master_port = 29500
    }
    cfg.pretrain_steps = parse_env_int("NEURX_PRETRAIN_STEPS", 1000000000)
    cfg.micro_batch = parse_env_int("NEURX_PRETRAIN_MICRO_BATCH", 1)
    cfg.seq_len = parse_env_int("NEURX_PRETRAIN_SEQ_LEN", 256)
    cfg.learning_rate = parse_env_float("NEURX_PRETRAIN_LR", 0.0002)
    cfg.log_interval = parse_env_int("NEURX_PRETRAIN_LOG_INTERVAL", 10)
    cfg.save_interval = parse_env_int("NEURX_PRETRAIN_SAVE_INTERVAL", 100)
    cfg.transformer_dim = parse_env_int("NEURX_TRANSFORMER_DIM", 1024)
    cfg.transformer_heads = parse_env_int("NEURX_TRANSFORMER_HEADS", 16)
    cfg.transformer_ffn = parse_env_int("NEURX_TRANSFORMER_FFN", 4096)
    cfg.transformer_layers = parse_env_int("NEURX_TRANSFORMER_NUM_LAYERS", 24)
    cfg.gradient_accumulation_steps = parse_env_int("NEURX_GRADIENT_ACCUMULATION_STEPS", 8)
    cfg.tokenizer_vocab = os_getenv("NEURX_TOKENIZER_VOCAB")
    if cfg.tokenizer_vocab == "" {
        cfg.tokenizer_vocab = root + "/data/corpus/vocab.json"
    }
    cfg.tokenizer_merges = os_getenv("NEURX_TOKENIZER_MERGES")
    if cfg.tokenizer_merges == "" {
        cfg.tokenizer_merges = root + "/data/corpus/merges.txt"
    }
    cfg.shard_list_file = os_getenv("NEURX_PRETRAIN_SHARD_LIST_FILE")
    if cfg.shard_list_file == "" {
        cfg.shard_list_file = root + "/artifact/build/run_large_pretrain/shard_list.txt"
    }
    return cfg
}

func parse_env_int(string key, int default_val) int {
    string val = os_getenv(key)
    if val == "" {
        return default_val
    }
    return strings_parse_int(val)
}

func parse_env_float(string key, float default_val) float {
    string val = os_getenv(key)
    if val == "" {
        return default_val
    }
    return strings_parse_float(val)
}

func parse_hostfile(string hostfile_path) []string {
    []string hosts = []string{}
    if !fs_exists(hostfile_path) {
        io_eprintln("hostfile not found: " + hostfile_path)
        return hosts
    }
    string content = fs_read_file(hostfile_path)
    []string lines = strings_split(content, "\n")
    for i := 0; i < len(lines); i++ {
        string line = strings_trim(lines[i])
        if line == "" || strings_has_prefix(line, "#") {
            continue
        }
        []string parts = strings_split(line, " ")
        if len(parts) >= 1 {
            hosts = append(hosts, line)
        }
    }
    return hosts
}

func generate_launcher_script(training_config cfg, []string hosts) string {
    string script = ""
    script = script + "#!/usr/bin/env bash\n"
    script = script + "set -Eeuo pipefail\n"
    script = script + "\n"
    script = script + "# Auto-generated by NeurX Launcher (S Language)\n"
    script = script + "# config: " + cfg.root_dir + "\n"
    script = script + "\n"
    script = script + "# Configuration\n"
    script = script + "ROOT=\"" + cfg.root_dir + "\"\n"
    script = script + "HOSTFILE=\"" + cfg.hostfile + "\"\n"
    script = script + "OUT=\"" + cfg.output_dir + "\"\n"
    script = script + "SHARED_ID=\"" + cfg.nccl_id_file + "\"\n"
    script = script + "MASTER_ADDR=\"" + cfg.master_addr + "\"\n"
    script = script + "MASTER_PORT=" + strings_from_int(cfg.master_port) + "\n"
    script = script + "\n"
    script = script + "# Base environment variables\n"
    script = script + "declare -a base_env=(\n"
    script = script + "  \"NEURX_ROOT=$ROOT\"\n"
    script = script + "  \"NEURX_PRETRAIN_OUTPUT_DIR=$OUT\"\n"
    script = script + "  \"NEURX_NCCL_ID_FILE=$SHARED_ID\"\n"
    script = script + "  \"NEURX_PRETRAIN_SHARD_LIST_FILE=" + cfg.shard_list_file + "\"\n"
    script = script + "  \"NEURX_PRETRAIN_STEPS=" + strings_from_int(cfg.pretrain_steps) + "\"\n"
    script = script + "  \"NEURX_PRETRAIN_MICRO_BATCH=" + strings_from_int(cfg.micro_batch) + "\"\n"
    script = script + "  \"NEURX_PRETRAIN_SEQ_LEN=" + strings_from_int(cfg.seq_len) + "\"\n"
    script = script + "  \"NEURX_PRETRAIN_LR=" + strings_from_float(cfg.learning_rate) + "\"\n"
    script = script + "  \"NEURX_PRETRAIN_LOG_INTERVAL=" + strings_from_int(cfg.log_interval) + "\"\n"
    script = script + "  \"NEURX_PRETRAIN_SAVE_INTERVAL=" + strings_from_int(cfg.save_interval) + "\"\n"
    script = script + "  \"NEURX_TRANSFORMER_DIM=" + strings_from_int(cfg.transformer_dim) + "\"\n"
    script = script + "  \"NEURX_TRANSFORMER_HEADS=" + strings_from_int(cfg.transformer_heads) + "\"\n"
    script = script + "  \"NEURX_TRANSFORMER_FFN=" + strings_from_int(cfg.transformer_ffn) + "\"\n"
    script = script + "  \"NEURX_TRANSFORMER_NUM_LAYERS=" + strings_from_int(cfg.transformer_layers) + "\"\n"
    script = script + "  \"NEURX_GRADIENT_ACCUMULATION_STEPS=" + strings_from_int(cfg.gradient_accumulation_steps) + "\"\n"
    script = script + "  \"NEURX_TOKENIZER_VOCAB=" + cfg.tokenizer_vocab + "\"\n"
    script = script + "  \"NEURX_TOKENIZER_MERGES=" + cfg.tokenizer_merges + "\"\n"
    script = script + "  \"MASTER_ADDR=$MASTER_ADDR\"\n"
    script = script + "  \"MASTER_PORT=$MASTER_PORT\"\n"
    script = script + "  \"WORLD_SIZE=" + strings_from_int(cfg.world_size) + "\"\n"
    script = script + ")\n"
    script = script + "\n"
    script = script + "# Cleanup function\n"
    script = script + "declare -a PIDS=()\n"
    script = script + "cleanup() {\n"
    script = script + "  trap - EXIT INT TERM\n"
    script = script + "  for pid in \"${PIDS[@]:-}\"; do kill \"$pid\" 2>/dev/null || true; done\n"
    script = script + "}\n"
    script = script + "trap cleanup EXIT INT TERM\n"
    script = script + "\n"
    script = script + "# Create output directories\n"
    script = script + "mkdir -p \"$(dirname \"$SHARED_ID\")\" \"$OUT\"\n"
    script = script + "rm -f \"$SHARED_ID\" \"$SHARED_ID.tmp\"\n"
    script = script + "\n"
    script = script + "echo \"[multinode] nodes=" + strings_from_int(len(hosts)) +
                      " world_size=" + strings_from_int(cfg.world_size) +
                      " master=${MASTER_ADDR}:${MASTER_PORT}\"\n"
    script = script + "echo \"[multinode] shared NCCL id: $SHARED_ID\"\n"
    script = script + "\n"
    script = script + "# Launch processes\n"
    script = script + "rank=0\n"
    script = script + "for node in " + generate_hosts_array(hosts) + "; do\n"
    script = script + "  host=\"${node%% *}\"; gpus=\"${node#* }\"\n"
    script = script + "  if [[ \"$gpus\" == \"$node\" || ! \"$gpus\" =~ ^[0-9]+$ ]]; then\n"
    script = script + "    gpus=\"$(nvidia-smi -L 2>/dev/null | wc -l)\"\n"
    script = script + "  fi\n"
    script = script + "  for ((local=0; local<gpus; local++)); do\n"
    script = script + "    # A single rank writes directly under OUT; distributed ranks use rank_N.\n"
    script = script + "    if (( world == 1 )); then\n"
    script = script + "      ckpt_path=\"$OUT/transformer_v2.ckpt\"\n"
    script = script + "    else\n"
    script = script + "      ckpt_path=\"$OUT/rank_${rank}/transformer_v2.ckpt\"\n"
    script = script + "    fi\n"
    script = script + "    cmd=(\"env\" \"${base_env[@]}\" \"RANK=$rank\" \"LOCAL_RANK=$local\"\n"
    script = script + "      \"CUDA_VISIBLE_DEVICES=$local\"\n"
    script = script + "      \"NEURX_PRETRAIN_RESUME_FROM=$ckpt_path\"\n"
    script = script + "      \"$ROOT/artifact/build/cuda_train/neurx_cuda_train_bridge\")\n"
    script = script + "    echo \"[multinode] rank=$rank host=$host local_rank=$local checkpoint=$ckpt_path\"\n"
    script = script + "    if [[ \"$host\" == \"localhost\" || \"$host\" == \"127.0.0.1\" || \"$host\" == \"$(hostname)\" ]]; then\n"
    script = script + "      \"${cmd[@]}\" 2>&1 | tee -a \"${OUT}/rank_${rank}.log\" &\n"
    script = script + "    else\n"
    script = script + "      printf -v remote_cmd '%q ' \"${cmd[@]}\"\n"
    script = script + "      ssh \"$host\" \"cd $(printf '%q' \"$ROOT\") && $remote_cmd\" >\"${OUT}/rank_${rank}.log\" 2>&1 &\n"
    script = script + "    fi\n"
    script = script + "    PIDS+=(\"$!\")\n"
    script = script + "    rank=$((rank + 1))\n"
    script = script + "  done\n"
    script = script + "done\n"
    script = script + "\n"
    script = script + "# Wait for all processes\n"
    script = script + "status=0\n"
    script = script + "for pid in \"${PIDS[@]}\"; do wait \"$pid\" || status=$; done\n"
    script = script + "exit \"$status\"\n"
    return script
}

func generate_hosts_array([]string hosts) string {
    string result = ""
    for i := 0; i < len(hosts); i++ {
        if i > 0 {
            result = result + " "
        }
        result = result + "\"" + hosts[i] + "\""
    }
    return result
}

func main() {
    training_config cfg = load_config_from_env()
    []string hosts = parse_hostfile(cfg.hostfile)
    if len(hosts) == 0 {
        io_eprintln("ERROR: no valid hosts in hostfile")
        os_exit(2)
    }
    cfg.num_nodes = len(hosts)
    cfg.world_size = 0
    for i := 0; i < len(hosts); i++ {
        cfg.world_size = cfg.world_size + 1
    }
    string script = generate_launcher_script(cfg, hosts)
    string output_script = cfg.root_dir + "/script/legacy/launch_multinode_pretrain_generated.sh"
    if !fs_write_file(output_script, script) {
        io_eprintln("ERROR: cannot write script to " + output_script)
        os_exit(1)
    }
    io_println("✓ Generated launcher script: " + output_script)
    os_chmod(output_script, 0755)
    io_println("✓ Ready to launch: bash " + output_script)
}
