from neurx.core import (
    Tensor,
    bmm,
    cat,
    chunk,
    eig,
    inverse,
    matmul,
    meshgrid,
    mm,
    split,
    stack,
    svd,
    no_grad,
    enable_grad,
    set_grad_enabled,
    is_grad_enabled,
    where,
    clamp,
    clip,
    sign,
    flip,
    roll,
    tile,
    softmax,
    log_softmax,
    take_along_dim,
    # Tensor creation functions
    zeros,
    ones,
    full,
    empty,
    rand,
    randn,
    randint,
    arange,
    linspace,
    logspace,
    eye,
    diag,
    zeros_like,
    ones_like,
    full_like,
    rand_like,
    randn_like,
)
from neurx.core.einsum import einsum
from neurx.version import __version__
try:
    from neurx import ad, compile, data, distributed, nn, optim, serialization, train, training, vision
except Exception:
    ad = compile = data = distributed = nn = optim = serialization = train = training = vision = None
try:
    from neurx.losses import cross_entropy, cross_entropy_loss
except Exception:
    cross_entropy = cross_entropy_loss = None
from neurx.platform import doctor, format_doctor_report, get_runtime_config, runtime_info
import numpy as np


def manual_seed(seed: int) -> None:
    np.random.seed(int(seed))

__all__ = [
    "__version__",
    "Tensor",
    "where",
    "clamp",
    "clip",
    "sign",
    "flip",
    "roll",
    "tile",
    "softmax",
    "log_softmax",
    "take_along_dim",
    "cat",
    "stack",
    "split",
    "chunk",
    "matmul",
    "mm",
    "bmm",
    "meshgrid",
    "inverse",
    "svd",
    "eig",
    "einsum",
    "no_grad",
    "enable_grad",
    "set_grad_enabled",
    "is_grad_enabled",
    "manual_seed",
    # Tensor creation functions
    "zeros",
    "ones",
    "full",
    "empty",
    "rand",
    "randn",
    "randint",
    "arange",
    "linspace",
    "logspace",
    "eye",
    "diag",
    "zeros_like",
    "ones_like",
    "full_like",
    "rand_like",
    "randn_like",
    # Modules
    "data",
    "ad",
    "distributed",
    "compile",
    "train",
    "nn",
    "optim",
    "serialization",
    "training",
    "vision",
    "cross_entropy",
    "cross_entropy_loss",
    "get_runtime_config",
    "runtime_info",
    "doctor",
    "format_doctor_report",
]
