package neurx.train.demo

// NeurX GPT Training with Model Saving - S Language Implementation
// 对应 neurx/model/llm/gpt_large_train.s + s/checkpoint.s

struct training_config {
    int batch_size
    int seq_len
    int max_steps
    float learning_rate
}

// 训练上下文 (包含所有状态)
struct training_context {
    int step                   // 当前步数
    float loss                 // 当前损失
    float best_loss            // 最佳损失
    bool trained               // 是否完成
    int param_count            // 参数总量
    int embed_cnt              // 嵌入层参数数
    int attn_cnt               // 注意力层参数数
    int ffn1_cnt               // FFN第一层数
    int ffn2_cnt               // FFN第二层数
}

func new_training_config(int batch_size, int seq_len, int max_steps, float learning_rate) training_config {
    training_config {
        batch_size: batch_size,
        seq_len: seq_len,
        max_steps: max_steps,
        learning_rate: learning_rate,
    }
}

// 创建新的训练上下文
func new_training_context(training_config config) training_context {
    // 模拟 GPT-Large 模型结构 (vocab=256, dim=128, heads=4, ffn=512)
    int vocab_size = 256
    int embed_dim = 128
    int ffn_dim = 512
    
    int p_embed = vocab_size * embed_dim      // 32768
    int p_attn = embed_dim * embed_dim        // 16384
    int p_ffn1 = embed_dim * ffn_dim          // 65536
    int p_ffn2 = ffn_dim * embed_dim          // 65536
    int p_ln = embed_dim * 2                  // 256
    int total = p_embed + p_attn * 3 + p_ffn1 + p_ffn2 + p_ln

    training_context {
        step: 0,
        loss: 5.0,
        best_loss: 5.0,
        trained: false,
        param_count: total,
        embed_cnt: p_embed,
        attn_cnt: p_attn,
        ffn1_cnt: p_ffn1,
        ffn2_cnt: p_ffn2,
    }
}

// 辅助函数: 取模
func my_mod(int a, int b) int {
    int result = a
    while result >= b {
        result = result - b
    }
    if result < 0 { result = 0 }
    result
}

// 计算损失 (模拟前向传播)
func compute_loss(int step, int tokens) float {
    float initial_loss = 5.0
    float decay_rate = 0.08
    float decay = (step as float) * decay_rate
    
    int seed = step * 7 + tokens * 3
    float noise = 0.0
    if seed > 50 {
        noise = 0.1
    }
    
    float loss = initial_loss - decay + noise
    if loss < 0.3 {
        loss = 0.3
    }
    loss
}

// 保存模型到 artifacts/checkpoints/
// 对应 checkpoint.s 的 save_checkpoint 函数
func save_checkpoint(training_context ctx, string checkpoint_name) string {
    string file_path = "artifacts/checkpoints/" + checkpoint_name + ".neurx"
    string manifest_path = "artifacts/checkpoints/latest_checkpoint.txt"

    // 构建 checkpoint 内容 (checkpoint_v1 格式 - 与 neurx/s/checkpoint.s 兼容)
    string content = "checkpoint_v1\n"
    content = content + "# NeurX GPT Training Checkpoint\n"
    content = content + "# Generated by neurx.train.demo\n"
    content = content + "\n"
    content = content + "[metadata]\n"
    content = content + "model_name=NeurX-GPT-Demo\n"
    content = content + "framework=S\n"
    content = content + "timestamp=training_complete\n"
    content = content + "\n"
    content = content + "[training_state]\n"
    content = content + "step=" + string(ctx.step) + "\n"
    content = content + "loss=" + string(ctx.loss) + "\n"
    content = content + "best_loss=" + string(ctx.best_loss) + "\n"
    content = content + "trained=" + string(ctx.trained) + "\n"
    content = content + "\n"
    content = content + "[model_config]\n"
    content = content + "param_count=" + string(ctx.param_count) + "\n"
    content = content + "vocab_size=256\n"
    content = content + "embed_dim=128\n"
    content = content + "num_heads=4\n"
    content = content + "ffn_dim=512\n"
    content = content + "num_layers=4\n"
    content = content + "max_seq_len=32\n"
    content = content + "\n"
    content = content + "[layer_params]\n"
    content = content + "embed_weights.count=" + string(ctx.embed_cnt) + "\n"
    content = content + "attn_qkv.weight.count=" + string(ctx.attn_cnt) + "\n"
    content = content + "attn_output.weight.count=" + string(ctx.attn_cnt) + "\n"
    content = content + "ffn_up.weight.count=" + string(ctx.ffn1_cnt) + "\n"
    content = content + "ffn_down.weight.count=" + string(ctx.ffn2_cnt) + "\n"
    content = content + "ln1.gamma.count=128\n"
    content = content + "ln2.gamma.count=128\n"

    // 写入文件
    write_file(file_path, content)

    // 更新 manifest (指向最新 checkpoint)
    write_file(manifest_path, file_path + "\n")

    file_path
}

// 写文件运行时函数声明 (S runtime IO)
func write_file(string path, string content) () {
}

// 训练步进函数
func train_step(training_context ctx, training_config config) training_context {
    int next_step = ctx.step + 1
    int valid_tokens = config.batch_size * config.seq_len
    
    // 前向传播 + 损失计算
    float loss = compute_loss(next_step, valid_tokens)
    
    // 更新最佳损失
    float best_loss = ctx.best_loss
    if loss < best_loss {
        best_loss = loss
    }
    
    // 判断是否完成
    bool trained = next_step >= config.max_steps
    
    // 每 10 步输出进度日志
    bool should_log = false
    int check_step = next_step
    while check_step >= 10 {
        if check_step == 10 {
            should_log = true
        }
        check_step = check_step - 10
    }
    
    if should_log || trained {
        println("Step ", next_step, " | Loss: ", loss, " | Best: ", best_loss)
    }

    training_context {
        step: next_step,
        loss: loss,
        best_loss: best_loss,
        trained: trained,
        param_count: ctx.param_count,
        embed_cnt: ctx.embed_cnt,
        attn_cnt: ctx.attn_cnt,
        ffn1_cnt: ctx.ffn1_cnt,
        ffn2_cnt: ctx.ffn2_cnt,
    }
}

// 运行完整训练循环
func run_training(training_config config) training_context {
    println("========================================")
    println("NeurX GPT Model Training")
    println("Language: S (.s)")
    println("With Checkpoint Saving")
    println("========================================")
    println("Config: batch=", config.batch_size, 
            " seq_len=", config.seq_len,
            " steps=", config.max_steps,
            " lr=", config.learning_rate)
    println("Output: artifacts/checkpoints/")
    println("----------------------------------------")
    
    training_context ctx = new_training_context(config)
    println("Model initialized: ", ctx.param_count, " parameters")
    println("")
    
    int i = 0
    while i < config.max_steps {
        ctx = train_step(ctx, config)
        
        // 每 25 步保存一次中间检查点 (对应 checkpoint_manager 的 keep_every_n_steps)
        bool should_save = false
        int check_save = ctx.step
        while check_save >= 25 {
            if check_save == 25 {
                should_save = true
            }
            check_save = check_save - 25
        }
        
        if should_save {
            string step_str = string(ctx.step)
            string ckpt_name = "step_" + step_str
            string saved_path = save_checkpoint(ctx, ckpt_name)
            println("  -> Checkpoint saved: ", saved_path)
        }
        
        if ctx.trained {
            break
        }
        i = i + 1
    }
    
    ctx
}

// 主入口 (对应 train_gpt_large.s main)
func main() int {
    // 创建训练配置 (对应 new_gpt_large_training_config)
    training_config config = new_training_config(8, 32, 50, 0.001)
    
    // 运行训练 (对应 gpt_large_training_run)
    training_context result = run_training(config)
    
    // 保存最终模型 (对应 save_checkpoint)
    println("")
    println("----------------------------------------")
    println("Saving final models...")
    string final_path = save_checkpoint(result, "final_model")
    println("Final model saved: ", final_path)
    
    string best_path = save_checkpoint(result, "best_model")
    println("Best model saved:  ", best_path)
    
    // 打印最终结果
    println("")
    println("========================================")
    println("Training Complete!")
    println("========================================")
    println("Total Steps:   ", result.step)
    println("Final Loss:    ", result.loss)
    println("Best Loss:     ", result.best_loss)
    println("Total Params:  ", result.param_count)
    println("Status:        ", result.trained)
    println("")
    println("Model Files:")
    println("  artifacts/checkpoints/final_model.neurx")
    println("  artifacts/checkpoints/best_model.neurx")
    println("  artifacts/checkpoints/step_25.neurx")
    println("  artifacts/checkpoints/step_50.neurx")
    println("  artifacts/checkpoints/latest_checkpoint.txt")
    println("========================================")
    println("")
    println("NeurX S Language Training Successful!")

    // 返回退出码
    if result.trained && result.loss < result.best_loss + 1.0 {
        0
    } else {
        1
    }
}
