#!/bin/bash
# NeurX级别工业LLM训练数据生成脚本
# 生成高质量的多样化训练数据集

NEURX_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)/neurx"
OUTPUT_FILE="$NEURX_HOME/data/training_data_neurx.jsonl"

echo "🚀 生成NeurX级别的工业LLM训练数据..."
echo ""

cat > "$OUTPUT_FILE" << 'TRAINING_DATA_EOF'
{"text":"# Python性能优化指南\n\n## 1. 使用NumPy进行矩阵运算\nNumPy提供的向量化操作比纯Python循环快100倍以上。\n```python\nimport numpy as np\n# 快速：向量化操作\na = np.array([1, 2, 3, 4])\nb = np.array([5, 6, 7, 8])\nc = np.dot(a, b)  # 结果: 70\n\n# 缓慢：Python循环\nc = sum(a[i] * b[i] for i in range(len(a)))\n```\n## 2. 使用列表推导式\n列表推导式通常比map/filter快。\n## 3. 使用缓存装饰器\n@lru_cache装饰器可以显著提升递归函数性能。"}
{"text":"# 大语言模型训练指南\n\n## 预训练阶段\n1. **数据准备**：收集高质量的文本数据，进行清洗和分词\n2. **模型架构**：使用Transformer架构，配置合适的隐藏层维度和注意力头数\n3. **训练策略**：\n   - 使用余弦退火学习率调度\n   - 应用梯度裁剪防止梯度爆炸\n   - 使用混合精度训练加速计算\n4. **检查点保存**：定期保存模型检查点，以便中断后恢复\n\n## 微调阶段\n- 在特定任务数据集上进行有监督微调(SFT)\n- 使用RLHF(强化学习从人类反馈)进一步优化\n- 应用指令跟随和对齐技术"}
{"text":"# 问题：如何使用Python实现快速排序算法？\n\n## 回答：\n快速排序是一种高效的分治排序算法。\n\n```python\ndef quick_sort(arr):\n    \"\"\"原地快速排序\"\"\"\n    if len(arr) <= 1:\n        return arr\n    \n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    middle = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    \n    return quick_sort(left) + middle + quick_sort(right)\n```\n\n### 时间复杂度\n- 平均情况：O(n log n)\n- 最坏情况：O(n²)\n\n### 空间复杂度\n- O(log n) 用于递归栈"}
{"text":"# 分布式训练的最佳实践\n\n## 梯度同步策略\n在多GPU/多节点训练中，梯度同步是关键：\n\n1. **AllReduce操作**：所有进程对梯度求和并广播\n2. **梯度累积**：在更新前累积多个batch的梯度\n3. **通信优化**：重叠计算和通信以降低延迟\n\n## 缩放效率\n- 理想情况：线性缩放 (N个GPU达到N倍加速)\n- 实际情况：通常80-95%的缩放效率\n- 关键因素：同步开销、通信延迟、负载不均衡\n\n## 推荐配置\n- Batch size：256-1024 (根据GPU内存调整)\n- 学习率：随GPU数量线性增加\n- 预热步数：约总步数的10%"}
{"text":"# 指令：请解释Transformer架构中的自注意力机制\n\n## 详细解释：\n\n自注意力机制是Transformer的核心，允许模型在处理每个token时关注序列中的所有位置。\n\n### 计算步骤\n1. **线性投影**：将输入投影到Query(Q)、Key(K)、Value(V)\n2. **相似度计算**：计算Q与K的点积，得到注意力权重\n3. **缩放**：除以sqrt(d_k)防止梯度消失\n4. **Softmax**：将权重归一化为概率分布\n5. **加权求和**：使用注意力权重对V进行加权求和\n\n### 多头注意力\n- 使用多组独立的Q、K、V投影\n- 并行计算多个注意力头\n- 最后拼接并线性投影得到输出\n\n### 复杂度分析\n- 时间复杂度：O(n²d)其中n是序列长度，d是隐藏维度\n- 空间复杂度：O(n²)用于注意力矩阵"}
{"text":"# 对话示例：AI助手与用户的交互\n\n用户：\"如何使用Python进行数据可视化？\"\n\n助手：\"Python提供多个强大的数据可视化库：\n\n1. **Matplotlib**：基础但功能强大\n   - 适合出版质量的图表\n   - 对底层细节的完全控制\n\n2. **Seaborn**：基于Matplotlib的高级库\n   - 更美观的默认样式\n   - 更易使用的统计图表API\n\n3. **Plotly**：交互式可视化\n   - 网页应用中展示动态图表\n   - 支持3D和地理可视化\n\n4. **Altair**：基于Vega-Lite的声明式库\n   - 简洁的语法\n   - 优秀的交互性能\n\n我建议根据用途选择：数据探索用Jupyter+Matplotlib，报告用Seaborn，网页应用用Plotly。\"\n\n用户：\"谢谢！那Plotly的性能如何？\"\n\n助手：\"Plotly的性能取决于数据点数量...\""}
{"text":"# 数学推理：证明快速排序的平均时间复杂度\n\n## 问题\n证明快速排序的平均时间复杂度为O(n log n)。\n\n## 证明\n设T(n)为排序n个元素所需的平均比较次数。\n\n假设主元将数组分为大小为k和n-1-k的两部分，其中k均匀分布在[0, n-1]中。\n\n**递推式**：\nT(n) = n - 1 + (1/n) * Σ(k=0 to n-1)[T(k) + T(n-1-k)]\n     = n - 1 + (2/n) * Σ(k=0 to n-1)[T(k)]\n\n**求解**：\n假设T(n) ≤ cn log n，我们可以用数学归纳法证明：\n\nT(n) = n - 1 + (2/n) * Σ(k=1 to n-1)[ck log k]\n     ≤ n - 1 + (2c/n) * ∫(1 to n)[x log x dx]\n     = n - 1 + (2c/n) * [n²/2 * log n - n²/4 + 1/4]\n     ≤ cn log n (当c足够大时)\n\n因此，快速排序的平均时间复杂度为**O(n log n)**。"}
{"text":"# 安全性和伦理考量\n\n## AI系统中的安全问题\n\n### 1. 对抗性攻击\n- **越狱提示**：精心设计的输入试图绕过安全措施\n- **后缀注入**：在提示末尾添加恶意内容\n- **防御**：多层检测和拒绝机制\n\n### 2. 信息安全\n- **隐私泄露**：训练数据中的个人信息\n- **知识产权**：生成受版权保护的内容\n- **防御**：数据脱敏和去识别处理\n\n### 3. 公平性和偏见\n- **性别偏见**：模型可能强化性别刻板印象\n- **种族偏见**：训练数据中的历史偏见\n- **防御**：多样化训练数据和持续监控\n\n### 4. 内容政策\n- 禁止非法内容：毒品、武器等\n- 禁止有害内容：仇恨言论、暴力\n- 禁止欺骗：深度伪造、虚假信息\n\n## 最佳实践\n1. 使用分类器预先过滤有害内容\n2. 实现拒绝策略\n3. 定期审计和改进"}
{"text":"# 代码补全示例\n\n## 示例1：实现一个通用的缓存装饰器\n```python\nfrom functools import wraps\nimport time\n\ndef cache_with_timeout(timeout_seconds=300):\n    \"\"\"带超时的缓存装饰器\"\"\"\n    def decorator(func):\n        cache = {}\n        cache_time = {}\n        \n        @wraps(func)\n        def wrapper(*args, **kwargs):\n            key = (args, tuple(sorted(kwargs.items())))\n            current_time = time.time()\n            \n            if key in cache:\n                cache_timestamp = cache_time[key]\n                if current_time - cache_timestamp < timeout_seconds:\n                    return cache[key]\n                else:\n                    del cache[key]\n                    del cache_time[key]\n            \n            result = func(*args, **kwargs)\n            cache[key] = result\n            cache_time[key] = current_time\n            return result\n        \n        return wrapper\n    return decorator\n\n# 使用示例\n@cache_with_timeout(timeout_seconds=60)\ndef expensive_computation(x):\n    \"\"\"耗时计算函数\"\"\"\n    return sum(i**2 for i in range(x))\n```\n\n## 示例2：实现一个自适应学习率调度器\n```python\nclass AdaptiveLRScheduler:\n    def __init__(self, optimizer, warmup_steps=1000, peak_lr=1e-3):\n        self.optimizer = optimizer\n        self.warmup_steps = warmup_steps\n        self.peak_lr = peak_lr\n        self.step_count = 0\n    \n    def step(self):\n        self.step_count += 1\n        if self.step_count <= self.warmup_steps:\n            # 线性预热\n            lr = self.peak_lr * (self.step_count / self.warmup_steps)\n        else:\n            # 余弦退火\n            progress = (self.step_count - self.warmup_steps) / (1000 - self.warmup_steps)\n            lr = 0.5 * self.peak_lr * (1 + math.cos(math.pi * progress))\n        \n        for param_group in self.optimizer.param_groups:\n            param_group['lr'] = lr\n```"}
{"text":"# 系统设计：构建一个可扩展的推荐系统\n\n## 架构概览\n```\n用户请求\n    ↓\n特征工程 → 候选生成 → 排序 → 结果返回\n    ↓        ↓         ↓\n  缓存     向量搜索   排序模型\n```\n\n## 组件详解\n\n### 1. 候选生成（Candidate Generation）\n- **协同过滤**：基于用户-项目交互\n- **内容推荐**：基于项目特征和用户偏好\n- **混合方法**：结合多个信号\n\n### 2. 排序（Ranking）\n- 使用更复杂的模型对候选进行排序\n- 考虑多个目标：点击率、转化率、用户满意度\n- 应用多任务学习框架\n\n### 3. 特征工程\n- **用户特征**：年龄、位置、历史行为\n- **项目特征**：类别、流行度、质量指标\n- **上下文特征**：时间、季节、设备类型\n\n### 4. 在线服务\n- **低延迟要求**：必须在100ms内响应\n- **缓存策略**：热点数据预缓存\n- **灰度发布**：新模型逐步推出\n\n## 性能优化\n1. 使用向量数据库加速相似度搜索\n2. 批量处理请求以提高吞吐\n3. 分层架构避免单点故障"}
{"text":"# 深度学习模型调试技巧\n\n## 常见问题诊断\n\n### 1. 梯度消失/爆炸\n**症状**：\n- 损失不下降或NaN\n- 权重更新几乎为零或变为无穷大\n\n**原因**：\n- 激活函数选择不当\n- 权重初始化不好\n- 网络过深\n\n**解决方案**：\n```python\n# 使用ReLU而不是Sigmoid\nmodel = nn.Sequential(\n    nn.Linear(input_size, hidden_size),\n    nn.ReLU(),  # 更好的梯度流\n    nn.Linear(hidden_size, output_size)\n)\n\n# 使用He初始化\nnn.init.kaiming_normal_(layer.weight)\n\n# 应用梯度裁剪\ntorch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)\n```\n\n### 2. 过拟合\n**症状**：\n- 训练损失持续下降\n- 验证损失上升\n\n**解决方案**：\n- 增加正则化强度\n- 减少模型容量\n- 增加训练数据\n- 应用Dropout\n\n### 3. 欠拟合\n**症状**：\n- 训练和验证损失都很高\n- 模型似乎没有学到任何有用的东西\n\n**解决方案**：\n- 增加模型容量\n- 训练更长时间\n- 减少正则化\n- 改进特征工程"}
{"text":"# API设计最佳实践\n\n## RESTful API原则\n1. **资源导向**：使用名词表示资源，不使用动词\n   - ✅ GET /users/123\n   - ✅ POST /users\n   - ❌ GET /getUser/123\n   - ❌ GET /deleteUser?id=123\n\n2. **HTTP方法语义**：\n   - GET：检索资源\n   - POST：创建新资源\n   - PUT：完整替换资源\n   - PATCH：部分更新资源\n   - DELETE：删除资源\n\n3. **版本管理**：\n   ```\n   /api/v1/users\n   /api/v2/users\n   ```\n\n4. **错误处理**：\n   ```json\n   {\n     \"error\": \"validation_failed\",\n     \"message\": \"用户名长度必须为3-20字符\",\n     \"status_code\": 400,\n     \"details\": {\n       \"field\": \"username\",\n       \"constraint\": \"length\"\n     }\n   }\n   ```\n\n## 安全考虑\n- 使用HTTPS加密通信\n- 实现速率限制防止滥用\n- 验证和授权所有请求\n- 记录敏感操作的日志\n- 使用CORS头控制跨域访问"}
{"text":"# 数据库优化技巧\n\n## 索引优化\n```sql\n-- 创建复合索引用于常见查询模式\nCREATE INDEX idx_user_date ON events(user_id, created_at DESC);\n\n-- 验证索引被使用\nEXPLAIN QUERY PLAN\nSELECT * FROM events WHERE user_id = 123 ORDER BY created_at DESC LIMIT 10;\n\n-- 定期检查未使用的索引\nSELECT * FROM pg_stat_user_indexes WHERE idx_scan = 0;\n```\n\n## 查询优化\n1. **避免N+1查询**：使用JOIN代替循环查询\n2. **分页查询**：对大结果集使用LIMIT和OFFSET\n3. **选择性查询**：只查询需要的列\n4. **批量操作**：使用INSERT INTO ... VALUES(...), (...) 批量插入\n\n## 连接池配置\n- 最小连接数：根据应用线程数设置\n- 最大连接数：通常为 min_connections * 2\n- 连接超时：30-60秒\n- 空闲超时：5-10分钟\n\n## 分片策略\n- **范围分片**：按日期或ID范围\n- **哈希分片**：按哈希值均匀分布\n- **地理分片**：按地区分布数据"}
{"text":"# 完整项目：从零构建文本分类系统\n\n## 问题定义\n建立一个系统，可以自动分类用户提交的技术问题为不同的类别（如Python、JavaScript、SQL等）。\n\n## 解决方案架构\n\n### 1. 数据准备\n```\n数据收集 → 数据清洗 → 数据标注 → 数据分割\n```\n\n### 2. 特征提取\n- TF-IDF：传统方法\n- Word2Vec/FastText：词向量\n- BERT嵌入：上下文感知\n\n### 3. 模型选择\n- 朴素贝叶斯：快速基线\n- SVM：非线性分类\n- 神经网络：最高准确率\n\n### 4. 评估指标\n- 准确率：(TP+TN)/(TP+TN+FP+FN)\n- 精准率：TP/(TP+FP)\n- 召回率：TP/(TP+FN)\n- F1分数：2*精准率*召回率/(精准率+召回率)\n\n### 5. 部署策略\n```\n模型训练 → A/B测试 → 灰度发布 → 完全发布 → 监控和告警\n```\n\n### 关键指标\n- 模型准确率≥95%\n- 推理延迟<100ms\n- 吞吐≥1000请求/秒\n\n## 成功因素\n1. 高质量的标注数据\n2. 合理的特征工程\n3. 持续的模型监控和改进"}
TRAINING_DATA_EOF

echo "✅ NeurX级别训练数据生成完成！"
echo ""
echo "📊 统计信息："
wc -l "$OUTPUT_FILE"
ls -lh "$OUTPUT_FILE"
echo ""
echo "📋 数据内容预览（前3条）："
head -3 "$OUTPUT_FILE" | cut -c1-150
echo ""
