master_addr: 112.29.145.3
master_port: 29500
npu_pretrain_config: cann/configs/ascend_910b_train.json

workers:
  - host: root@112.29.145.15
    visible_devices: 0
  - host: root@112.29.145.20
    visible_devices: 0
  - host: root@112.29.145.21
    visible_devices: 0
  - host: root@112.29.145.22
    visible_devices: 0
  - host: root@112.29.145.23
    visible_devices: 0
  - host: root@112.29.145.24
    visible_devices: 0
  - host: root@112.29.145.25
    visible_devices: 0
  - host: root@112.29.145.26
    visible_devices: 0
  - host: root@112.29.145.27
    visible_devices: 0
  - host: root@112.29.145.16
    visible_devices: 0
  - host: root@112.29.145.17
    visible_devices: 0
  - host: root@112.29.145.18
    visible_devices: 0
