#define NEURX_TRANSFORMER_INTEGRATION_NO_MAIN
#include "transformer_integration_test.cu"
#include <filesystem>
#include <fstream>
#include <sstream>
static int ei(const char*n,int d){const char*s=getenv(n);return s&&*s?atoi(s):d;}static float ef(const char*n,float d){const char*s=getenv(n);return s&&*s?strtof(s,nullptr):d;}static std::string es(const char*n,std::string d){const char*s=getenv(n);return s&&*s?s:d;}
struct header{char magic[8];int version,step,cursor,vocab,seq,dim,heads,ffn;};
static bool save(GM&m,const std::string&dir,int st,int cursor){cuda_device_synchronize();std::filesystem::create_directories(dir);std::string tmp=dir+"/transformer.ckpt.tmp",dst=dir+"/transformer.ckpt";std::ofstream o(tmp,std::ios::binary|std::ios::trunc);header h{{'N','X','T','R','F','M','R','1'},1,st,cursor,m.c.vocab,m.c.seq,m.c.dim,m.c.heads,m.c.ffn};o.write((char*)&h,sizeof(h));for(GP*p:m.ps()){o.write((char*)p->v,p->n*4);o.write((char*)p->m,p->n*4);o.write((char*)p->s,p->n*4);}o.close();if(!o)return false;std::filesystem::rename(tmp,dst);std::ofstream meta(dir+"/final_model.neurx");meta<<"{\n  \"architecture\": \"decoder_only_transformer\",\n  \"tokenizer\": \"byte_level\",\n  \"step\": "<<st<<",\n  \"vocab_size\": "<<m.c.vocab<<",\n  \"context_length\": "<<m.c.seq<<",\n  \"hidden_size\": "<<m.c.dim<<",\n  \"num_heads\": "<<m.c.heads<<",\n  \"ffn_size\": "<<m.c.ffn<<",\n  \"checkpoint\": \""<<dst<<"\"\n}\n";printf("[transformer] checkpoint-saved step=%d path=%s\n",st,dst.c_str());return true;}
static bool load(GM&m,const std::string&dir,int&st,int&cursor){std::ifstream in(dir+"/transformer.ckpt",std::ios::binary);if(!in)return false;header h{};in.read((char*)&h,sizeof(h));if(std::string(h.magic,8)!="NXTRFMR1"||h.vocab!=m.c.vocab||h.seq!=m.c.seq||h.dim!=m.c.dim||h.heads!=m.c.heads||h.ffn!=m.c.ffn)return false;for(GP*p:m.ps()){in.read((char*)p->v,p->n*4);in.read((char*)p->m,p->n*4);in.read((char*)p->s,p->n*4);}if(!in)return false;st=h.step;cursor=h.cursor;printf("[transformer] checkpoint-restored step=%d cursor=%d\n",st,cursor);return true;}
static std::vector<unsigned char> corpus(const std::string&list,size_t cap){std::ifstream l(list);std::vector<unsigned char>d;std::string p;while(std::getline(l,p)&&d.size()<cap){std::ifstream f(p,std::ios::binary);char c;while(d.size()<cap&&f.get(c))d.push_back((unsigned char)c);}return d;}
static void generate(GM&m,GC&a,std::string text,int count){for(int n=0;n<count;n++){int used=std::min(m.c.seq,(int)text.size()),pad=m.c.seq-used,start=(int)text.size()-used;for(int i=0;i<m.c.seq;i++)a.ids[i]=i<pad?0:(unsigned char)text[start+i-pad];for(int i=0;i<m.c.seq;i++)a.targets[i]=0;step(m,a);int row=m.c.seq-1,best=0;for(int j=1;j<m.c.vocab;j++)if(a.logits[row*m.c.vocab+j]>a.logits[row*m.c.vocab+best])best=j;text.push_back((char)best);}printf("[transformer] generated=%s\n",text.c_str());}
int main(){config c;c.vocab=256;c.seq=ei("NEURX_PRETRAIN_SEQ_LEN",32);c.dim=ei("NEURX_TRANSFORMER_DIM",64);c.heads=ei("NEURX_TRANSFORMER_HEADS",4);c.ffn=ei("NEURX_TRANSFORMER_FFN",192);if(c.dim%c.heads){fprintf(stderr,"hidden size must divide heads\n");return 2;}GM m(c);model init(c);auto a0=init.params();auto a1=m.ps();for(size_t p=0;p<a0.size();p++)for(int i=0;i<a1[p]->n;i++)a1[p]->v[i]=(float)a0[p]->v[i];GC ca=cache(c);std::string out=es("NEURX_PRETRAIN_OUTPUT_DIR","checkpoint/NeurX-Transformer"),list=es("NEURX_PRETRAIN_SHARD_LIST_FILE","artifacts/build/run_large_pretrain/shard_list.txt");int total=ei("NEURX_PRETRAIN_STEPS",1000),save_every=ei("NEURX_PRETRAIN_SAVE_INTERVAL",100),log_every=ei("NEURX_PRETRAIN_LOG_INTERVAL",10),st=0,pos=0;float lr=ef("NEURX_PRETRAIN_LR",.001f);if(ei("NEURX_PRETRAIN_RESUME",1))load(m,out,st,pos);auto data=corpus(list,(size_t)ei("NEURX_TRANSFORMER_CORPUS_BYTES",64*1024*1024));if(data.size()<(size_t)c.seq+1){fprintf(stderr,"corpus too small\n");return 3;}printf("[transformer] architecture=decoder_only_transformer vocab=%d seq=%d dim=%d heads=%d ffn=%d data=%zu start=%d total=%d\n",c.vocab,c.seq,c.dim,c.heads,c.ffn,data.size(),st,total);for(int s=st+1;s<=total;s++){if(pos+c.seq+1>(int)data.size())pos=0;for(int i=0;i<c.seq;i++){ca.ids[i]=data[pos+i];ca.targets[i]=data[pos+i+1];}if(!step(m,ca))return 4;update(m,s,lr);pos+=c.seq;if(s==1||s%log_every==0)printf("[transformer] step=%d/%d loss=%.6f cursor=%d\n",s,total,*ca.loss,pos);if(s%save_every==0&&!save(m,out,s,pos))return 5;st=s;}save(m,out,st,pos);generate(m,ca,es("NEURX_TRANSFORMER_PROMPT","Hello"),ei("NEURX_TRANSFORMER_GENERATE_TOKENS",32));return 0;}
