#include "transformer_kernels.cuh"
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <vector>
using namespace neurx_cuda_transformer;
#define CU(x) do{cuda_error_t e=(x);if(e!=cuda_success){std::fprintf(stderr,"CUDA %s:%d %s\n",__FILE__,__LINE__,cuda_get_error_string(e));return 2;}}while(0)
template<class T>T* managed(int n){T*p=nullptr;cuda_malloc_managed(&p,sizeof(T)*n);return p;}
static bool close(const char* name,const float* got,const std::vector<float>& want,int n,float tol=2e-5f){float e=0;for(int i=0;i<n;i++)e=std::max(e,std::abs(got[i]-want[i]));std::printf("cuda-%s %s max_abs_error=%.3g\n",name,e<tol?"PASS":"FAIL",e);return e<tol;}
int main(){bool ok=true;int m=3,kd=4,n=5;float*a=managed<float>(m*kd),*b=managed<float>(kd*n),*c=managed<float>(m*n),*dy=managed<float>(m*n),*dx=managed<float>(m*kd),*dw=managed<float>(kd*n);
 for(int i=0;i<m*kd;i++)a[i]=(i-4)*.03f;for(int i=0;i<kd*n;i++)b[i]=(i%7-3)*.02f;for(int i=0;i<m*n;i++)dy[i]=(i%5-2)*.04f;
 gemm_fwd<<<blocks(m*n),256>>>(a,b,c,m,kd,n);gemm_dx<<<blocks(m*kd),256>>>(dy,b,dx,m,kd,n);gemm_dw<<<blocks(kd*n),256>>>(a,dy,dw,m,kd,n);CU(cuda_device_synchronize());std::vector<float>ec(m*n),edx(m*kd),edw(kd*n);
 for(int i=0;i<m;i++)for(int p=0;p<kd;p++)for(int j=0;j<n;j++){ec[i*n+j]+=a[i*kd+p]*b[p*n+j];edx[i*kd+p]+=dy[i*n+j]*b[p*n+j];edw[p*n+j]+=a[i*kd+p]*dy[i*n+j];}ok&=close("gemm-forward",c,ec,m*n);ok&=close("gemm-dx",dx,edx,m*kd);ok&=close("gemm-dw",dw,edw,kd*n);
 int rows=3,d=8;float*x=managed<float>(rows*d),*g=managed<float>(d),*y=managed<float>(rows*d),*inv=managed<float>(rows),*rdy=managed<float>(rows*d),*rdx=managed<float>(rows*d),*rdg=managed<float>(d);
 for(int i=0;i<rows*d;i++){x[i]=(i%11-5)*.07f;rdy[i]=(i%9-4)*.03f;}for(int i=0;i<d;i++)g[i]=.8f+i*.02f;rms_fwd<<<1,32>>>(x,g,y,inv,rows,d);rms_dx<<<1,32>>>(x,g,inv,rdy,rdx,rows,d);rms_dg<<<1,32>>>(x,inv,rdy,rdg,rows,d);CU(cuda_device_synchronize());std::vector<float>ey(rows*d),edxr(rows*d),edgr(d);for(int r=0;r<rows;r++){float ss=0;for(int j=0;j<d;j++)ss+=x[r*d+j]*x[r*d+j];float z=1/std::sqrt(ss/d+1e-5f),dot=0;for(int j=0;j<d;j++){ey[r*d+j]=x[r*d+j]*z*g[j];dot+=rdy[r*d+j]*g[j]*x[r*d+j];edgr[j]+=rdy[r*d+j]*x[r*d+j]*z;}for(int j=0;j<d;j++)edxr[r*d+j]=rdy[r*d+j]*g[j]*z-x[r*d+j]*z*z*z*dot/d;}ok&=close("rms-forward",y,ey,rows*d);ok&=close("rms-dx",rdx,edxr,rows*d);ok&=close("rms-dgamma",rdg,edgr,d);
 int t=4,heads=2,hd=d/heads;float*q=managed<float>(t*d),*orig=managed<float>(t*d);for(int i=0;i<t*d;i++)q[i]=orig[i]=(i%13-6)*.04f;rope<<<1,64>>>(q,t,d,heads,false);rope<<<1,64>>>(q,t,d,heads,true);CU(cuda_device_synchronize());std::vector<float>eorig(orig,orig+t*d);ok&=close("rope-forward-backward",q,eorig,t*d,3e-6f);
 int sn=24;float*ga=managed<float>(sn),*up=managed<float>(sn),*so=managed<float>(sn),*sdy=managed<float>(sn),*sdg=managed<float>(sn),*sdu=managed<float>(sn);std::vector<float>eso(sn),esdg(sn),esdu(sn);for(int i=0;i<sn;i++){ga[i]=(i%7-3)*.2f;up[i]=(i%5-2)*.1f;sdy[i]=(i%3-1)*.3f;float s=1/(1+std::exp(-ga[i]));eso[i]=ga[i]*s*up[i];esdg[i]=sdy[i]*up[i]*(s+ga[i]*s*(1-s));esdu[i]=sdy[i]*ga[i]*s;}swiglu_fwd<<<1,32>>>(ga,up,so,sn);swiglu_bwd<<<1,32>>>(ga,up,sdy,sdg,sdu,sn);CU(cuda_device_synchronize());ok&=close("swiglu-forward",so,eso,sn);ok&=close("swiglu-dgate",sdg,esdg,sn);ok&=close("swiglu-dup",sdu,esdu,sn);
 int vocab=7;float*logits=managed<float>(t*vocab),*loss=managed<float>(1),*dl=managed<float>(t*vocab);int*target=managed<int>(t);std::vector<float>edl(t*vocab);*loss=0;float eloss=0;for(int i=0;i<t*vocab;i++)logits[i]=(i%9-4)*.1f;for(int r=0;r<t;r++){target[r]=(r+2)%vocab;float mx=*std::max_element(logits+r*vocab,logits+(r+1)*vocab),sum=0;for(int j=0;j<vocab;j++)sum+=std::exp(logits[r*vocab+j]-mx);eloss+=(std::log(sum)+mx-logits[r*vocab+target[r]])/t;for(int j=0;j<vocab;j++)edl[r*vocab+j]=(std::exp(logits[r*vocab+j]-mx)/sum-(j==target[r]))/t;}cross_entropy_fwd_bwd<<<1,32>>>(logits,target,loss,dl,t,vocab);CU(cuda_device_synchronize());ok&=std::abs(*loss-eloss)<2e-6f;std::printf("cuda-cross-entropy-loss %s abs_error=%.3g\n",std::abs(*loss-eloss)<2e-6f?"PASS":"FAIL",std::abs(*loss-eloss));ok&=close("cross-entropy-backward",dl,edl,t*vocab);
 float*aq=managed<float>(t*d),*ak=managed<float>(t*d),*av=managed<float>(t*d),*att=managed<float>(heads*t*t),*ctx=managed<float>(t*d),*dctx=managed<float>(t*d),*adq=managed<float>(t*d),*adk=managed<float>(t*d),*adv=managed<float>(t*d);for(int i=0;i<t*d;i++){aq[i]=(i%7-3)*.06f;ak[i]=(i%11-5)*.04f;av[i]=(i%5-2)*.08f;dctx[i]=(i%3-1)*.07f;}CU(cuda_memset(att,0,heads*t*t*sizeof(float)));CU(cuda_memset(adq,0,t*d*sizeof(float)));CU(cuda_memset(adk,0,t*d*sizeof(float)));CU(cuda_memset(adv,0,t*d*sizeof(float)));attention_fwd<<<heads*t,1>>>(aq,ak,av,att,ctx,t,d,heads);attention_bwd<<<heads*t,1,2*t*sizeof(float)>>>(aq,ak,av,att,dctx,adq,adk,adv,t,d,heads);CU(cuda_device_synchronize());
 auto host_loss=[&](){float s=0;std::vector<float>ha(heads*t*t),hc(t*d);for(int h=0;h<heads;h++)for(int i=0;i<t;i++){float mx=-1e30f;for(int j=0;j<=i;j++){float z=0;for(int p=0;p<hd;p++)z+=aq[i*d+h*hd+p]*ak[j*d+h*hd+p];ha[(h*t+i)*t+j]=z/std::sqrt(float(hd));mx=std::max(mx,ha[(h*t+i)*t+j]);}float su=0;for(int j=0;j<=i;j++)su+=std::exp(ha[(h*t+i)*t+j]-mx);for(int j=0;j<=i;j++)ha[(h*t+i)*t+j]=std::exp(ha[(h*t+i)*t+j]-mx)/su;for(int p=0;p<hd;p++)for(int j=0;j<=i;j++)hc[i*d+h*hd+p]+=ha[(h*t+i)*t+j]*av[j*d+h*hd+p];}for(int i=0;i<t*d;i++)s+=hc[i]*dctx[i];return s;};float maxe=0,eps=1e-3f;for(int z=0;z<t*d;z+=3){float old=aq[z];aq[z]=old+eps;float p=host_loss();aq[z]=old-eps;float mm=host_loss();aq[z]=old;maxe=std::max(maxe,std::abs((p-mm)/(2*eps)-adq[z]));old=ak[z];ak[z]=old+eps;p=host_loss();ak[z]=old-eps;mm=host_loss();ak[z]=old;maxe=std::max(maxe,std::abs((p-mm)/(2*eps)-adk[z]));old=av[z];av[z]=old+eps;p=host_loss();av[z]=old-eps;mm=host_loss();av[z]=old;maxe=std::max(maxe,std::abs((p-mm)/(2*eps)-adv[z]));}std::printf("cuda-causal-attention-backward %s max_abs_error=%.3g\n",maxe<2e-4?"PASS":"FAIL",maxe);ok&=maxe<2e-4;
 std::printf("cuda-transformer-kernels %s\n",ok?"PASS":"FAIL");return ok?0:1;
}
