/*
 * This file is automatically generated by Qt Design Studio.
 * Do not change.
*/

#include <QGuiApplication>

void set_qt_environment()
{
    // Let the system IME (fcitx/ibus) take effect; only fall back to
    // qtvirtualkeyboard when nothing else is configured.
    if (qEnvironmentVariable("QT_IM_MODULE").isEmpty())
        qputenv("QT_IM_MODULE", "fcitx");
    qputenv("QT_AUTO_SCREEN_SCALE_FACTOR", "1");
    qputenv("QT_ENABLE_HIGHDPI_SCALING", "0");
    qputenv("QT_LOGGING_RULES", "qt.qml.connections=false");
    qputenv("QT_QUICK_CONTROLS_CONF", ":/qtquickcontrols2.conf");
    qputenv("QML_COMPAT_RESOLVE_URLS_ON_ASSIGNMENT", "1");
}
